### ISSUE TITLE
Layout of Website broken (again)

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/isaqb-org.github.io#11]
after fixing #10, the layout of the site is completely broken again:

I built with gradle and (simply) pushed the updated index.html...

I assume that the instructions in readme are not complete :-)

sorry to have messed it up....

**Comment by aheusingfeld** [comment]
The reason is that you removed all CSS. If you put it back in, the site should be shiny again ;)

**Comment by programming-wolf** [comment]
Did you checkout the submodule? :-) it contains the css stuff.

**Comment by gernotstarke** [comment]
no, of course not... nothing mentioned in readme ...
but: tried again, looks better now.
