### ISSUE TITLE
please add build + deploy instructions to readme

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/isaqb-org.github.io#12]
with the introduction of the submodule, things have gotten more complicated than they were before - and currently this is not reflected in the readme...

**Comment by aheusingfeld** [comment]
https://github.com/isaqb-org/isaqb-org.github.io/commit/8b42b90e496f3ed922efb161d270656971b70661 added a note to the readme that you have to `git clone --recurse-submodules` in order to include the html-theme submodule
