### ISSUE TITLE
Add Automatic Buildpipeline

### ISSUE THREAD

**Issue by programming-wolf** [isaqb-org/isaqb-org.github.io#7]
We can use the GitHub actions of the other curriculum repositories to automatically update this repository. 
In addition, the pipeline could parse the `document.version` files of the other repositories to display proper release numbers _and_ reduce manual workload.

**Comment by gernotstarke** [comment]
+1 😁

**Comment by gernotstarke** [comment]
due to the low number of changes, I suppose this is not required. Shall we close it? There's more important stuff to do, imho

**Comment by programming-wolf** [comment]
Automate all the things. :-)
But yes, we can close it for the moment. If I have more time (maybe Christmas), I'll update some stuff.

**Comment by gernotstarke** [comment]
we will find even more important things for you to do over christmas. ADOC, IMPROVE and other curricula need love and intensive-care... or we update our arc42-primer, or such things...
